# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03b7c2beee6ed2d01591811f02a14952c7983ee7ddf14dabb1b62fdc5d495adc06f89c988b0a6691b51a6dd06953c3fb32c5ed6c89c1e60184af9dc7c52d3d11

test:
  secret_key_base: c8b8088e6906affad90d8a69357ec5ad573f0fab8ac2b19b9ba728c9c5a69fab3c59858a7dd5c8b266a6227f0ec0d756442de93a6b13a178296fbca78b2f46c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
